### ISSUE TITLE
Musketeer client joining server critical error

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [VazkiiMods/Musketeer#20]
### Versions

Minecraft: 1.19.2
Forge: 43.3.2
Musketeer 1.0.4
### Issue

I updated my Musketeer client and server from 1.0.3 to 1.0.4 using PrismLauncher.
Upon joining my own server, it says my client and server has a mod mismatch.
Windswept is version 2.2.2 on the server, but 2.2.3 on my client.
Changing either the client or server mod to match versions produces the same error.

![image](https://github.com/VazkiiMods/Musketeer/assets/87587913/65f4a009-09ad-415f-8f23-66d09c8295b7)

This error log is from me changing my client's Windswept version to 2.2.2.

https://gist.github.com/GameGuruGreenGryphon/961a27fa7a7a0c711a3569c1c65c6500

**Comment by Vazkii** [comment]
This is not a musketeer crash, look at the end of the file:
`[21:10:37] [Netty Client IO #3/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [supplementaries, collective, map_atlases, brokenitems, everycomp, chalk, emi, moonlight, lychee]`

Your installation just didnt go properly on the server side.
