### ISSUE TITLE
Iron EMI Usage typo

### ISSUE THREAD

**Issue by Ldawsonm** [VazkiiMods/Musketeer#5]
![image](https://github.com/VazkiiMods/Musketeer/assets/82904040/c3ab63f0-7b6c-40dd-bc03-adfd36e6eaee)

Hello, I just found a small typo in the EMI usage of Iron. It says "Iron Golems no longer drop Iron Ingots, try Toretoises instaed". That's all.

Great modpack btw

**Comment by Vazkii** [comment]
"Toretoise" is not a typo, it's the mob's name. T**ore**toise.

**Comment by Ldawsonm** [comment]
No, I'm talking about the word instaed.
